### ISSUE TITLE
Cache the unfollowers from the last week in a file

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/who-unfollowed-me#6]
Currently, users only have one chance at viewing unfollowers since last run. After that the files in `~/.unfollow` are updated!

Add a `--cached` option which allows users to view unfollowers from the last week as part of the info passed into `beautify.py`. The cached unfollowers should be in `.unfollow/cached.[txt|json]` (whichever format you choose)

**Comment by tintinthong** [comment]
Howdy. Can I work on this?

**Comment by TechWiz-3** [comment]
Sure 👍 
=

**Comment by TechWiz-3** [comment]
Any updates? @tintinthong

**Comment by tintinthong** [comment]
Owh r u in a rush for this? I'll pick it up over the weekend. If ur in a rush, feel free to unassign

**Comment by TechWiz-3** [comment]
No no, was just wondering, take your time 👍

**Comment by tintinthong** [comment]
@TechWiz-3 I have a clarifying question

This issue not that straightforward is because it only depends when the user last visited and run the unfollow command (becos thats how the cache develops). I should have clarified this sooner. 

For example, 

User runs command on monday and has 1 unfollower. Here are possible next steps

**Scenario 1**

- user comes back tuesday (same week) and runs command again
- What does the cache contain?

**Scenario 2**

- user comes back tuesday (next week) and runs command again
- What does the cache contain? 


**Scenario 3**

- user comes back tuesday (next next week) and runs command again
- What does the cache contain? 


@TechWiz-3 can you give answers to the questions above.  I guess it would be dependent on what you seek to do with your cache and how it is different from the previous non-cache implementation





-
